"""
Django settings for AuctionHouse project.

Generated by 'django-admin startproject' using Django 5.2.5.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os
import dj_database_url
from django.contrib.messages import constants as messages

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure--_lx4*%4c6t#i6a($ec-tet7xvio7qs14)&dkz5xlki30inv3q"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ["auction-house-5.onrender.com",'127.0.0.1']


UNFOLD = {
    "SITE_TITLE": "EasyBid Admin",
    "SITE_HEADER": "EasyBid",
    "SITE_URL": "/",
    "SITE_ICON": None,

    # --- THEME SETTINGS ---
    "SHOW_THEME_SWITCHER": True,

    # --- COLOR PALETTE ---
    "COLORS": {
        "primary": {
            "50": "#f5f3ff",
            "100": "#ede9fe",
            "200": "#ddd6fe",
            "300": "#c4b5fd",
            "400": "#a78bfa",
            "500": "#7c3aed",
            "600": "#6d28d9",
            "700": "#4c1d95",
            "800": "#371a63",
            "900": "#2e1065",
            "950": "#1e0b3b",
        },
    },

    # --- SIDEBAR NAVIGATION ---
    "SIDEBAR": {
        "show_search": True,
        "show_all_applications": False,
        "navigation": [
            {
                "title": "Auction List",
                "separator": True,
                "items": [

                    {"title": "Auctions", "icon": "gavel", "link": "/admin/auction_list/auction/"},
                    {"title": "Categories", "icon": "grid_view", "link": "/admin/auction_list/catagory/"},
                    {"title": "Invoices", "icon": "receipt_long", "link": "/admin/auction_list/invoice/"},
                    {"title": "Items", "icon": "category", "link": "/admin/auction_list/item/"},
                    {"title": "Lots", "icon": "inventory_2", "link": "/admin/auction_list/lot/"},
                ],
            },
            {
                "title": "Authentication",
                "separator": True,
                "items": [
                    {"title": "Groups", "icon": "group", "link": "/admin/auth/group/"},
                    {"title": "Users", "icon": "person", "link": "/admin/auth/user/"},
                ],
            },
            {
                "title": "Bids & Finances",
                "separator": True,
                "items": [
                    {"title": "Admin wallets", "icon": "account_balance", "link": "/admin/bids/adminwallet/"},
                    {"title": "Bids", "icon": "monetization_on", "link": "/admin/bids/bid/"},
                    {"title": "Transactions", "icon": "paid", "link": "/admin/bids/transaction/"},
                    {"title": "Wallets", "icon": "wallet", "link": "/admin/bids/wallet/"},
                ],
            },
            {
                "title": "Home",
                "separator": True,
                "items": [
                    {"title": "Profiles", "icon": "account_circle", "link": "/admin/Home/profile/"},
                ],
            },
        ],
    },

    # --- GENERAL SETTINGS ---
    "TABS": [],
    "LIST_VIEW": {
        "compact": False,
        "sticky_header": True,
    },
    "FORM": {
        "show_collapsible_help": True,
        "horizontal_fields": True,
        "show_help_text": True,
    },
    "BREADCRUMBS": True,
}



# Application definition

INSTALLED_APPS = [
    "daphne",
    "unfold",
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "whitenoise.runserver_nostatic",
    "Home",
    "auction_list",
    "bids",
    "channels",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
]

ROOT_URLCONF = "AuctionHouse.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [
            BASE_DIR / "templates",
            BASE_DIR / "Home/templates",
            BASE_DIR / "auction_list/templates",
            BASE_DIR / "custom_admin/templates",
            BASE_DIR / "bids/templates",
        ],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "AuctionHouse.wsgi.application"
# ASGI Configuration
ASGI_APPLICATION = "AuctionHouse.asgi.application"

# Channels Layer (for WebSocket)
CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "channels_redis.core.RedisChannelLayer",
        "CONFIG": {
            "hosts": [os.environ.get('REDIS_URL', 'redis://localhost:6379')],
        },
    },
}

# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    "default": dj_database_url.config(default="sqlite:///db.sqlite3")
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "Asia/Kolkata"  # Indian Standard Time (IST)

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = "static/"
STATICFILES_DIRS = [os.path.join(BASE_DIR, "static")]

STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
STATICFILES_STORAGE = "whitenoise.storage.CompressedManifestStaticFilesStorage"

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

MEDIA_URL = "/media/"
MEDIA_ROOT = os.path.join(BASE_DIR, "media")

MESSAGE_TAGS = {
    messages.DEBUG: "debug",
    messages.INFO: "info",
    messages.SUCCESS: "success",
    messages.WARNING: "warning",
    messages.ERROR: "error",
}

MESSAGE_LEVEL = messages.DEBUG

MESSAGE_STORAGE = "django.contrib.messages.storage.session.SessionStorage"

EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
EMAIL_HOST = "smtp.gmail.com"
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = "meetvaghasiya166@gmail.com"  # Replace with your email
EMAIL_HOST_PASSWORD = (
    "uycl kjms nuuh bysv"  # Replace with your password or app password
)

# Auction Settings  
WINNER_PAYMENT_TIMEOUT_MINUTES = 15

# Warehouse Location for Shipping Calculation
WAREHOUSE_CITY = 'Ahmedabad'
WAREHOUSE_STATE = 'Gujarat'

CSRF_TRUSTED_ORIGINS = [
    "https://auction-house-5.onrender.com",
]

CSRF_COOKIE_SECURE = True
SESSION_COOKIE_SECURE = True

CSRF_COOKIE_SAMESITE = "Lax"
SESSION_COOKIE_SAMESITE = "Lax"

SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

# Required for WebSockets behind proxy
USE_X_FORWARDED_HOST = True
SECURE_SSL_REDIRECT = True