"""
Django settings for AuctionHouse project.

Generated by 'django-admin startproject' using Django 5.2.5.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os
from django.contrib.messages import constants as messages

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure--_lx4*%4c6t#i6a($ec-tet7xvio7qs14)&dkz5xlki30inv3q"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['localhost', '127.0.0.1', '10.252.244.253', '*']


JAZZMIN_SETTINGS = {
    # --------------------------------------------------
    # BRANDING
    # --------------------------------------------------
    "site_title": "Auction Admin",
    "site_header": "Auction House",
    "site_brand": "Auction House",
    "site_logo": None,  # add path if you have logo
    "login_logo": None,
    "login_logo_dark": None,
    "site_icon": None,
    "welcome_sign": "Welcome to Auction Admin Panel",
    "copyright": "Auction House © 2026",
    # --------------------------------------------------
    # UI BEHAVIOR
    # --------------------------------------------------
    "show_sidebar": True,
    "navigation_expanded": True,
    "hide_apps": [],
    "hide_models": [],
    "order_with_respect_to": [
        "auction_list",
        "auth",
    ],
    # --------------------------------------------------
    # TOP MENU LINKS
    # --------------------------------------------------
    "topmenu_links": [
        {"name": "Dashboard", "url": "admin:index", "permissions": ["auth.view_user"]},
        {"name": "View Site", "url": "/", "new_window": True},
    ],
    # --------------------------------------------------
    # USER MENU LINKS
    # --------------------------------------------------
    "usermenu_links": [
        {"name": "Profile", "url": "/profile/", "icon": "fas fa-user"},
        {"model": "auth.user"},
    ],
    # --------------------------------------------------
    # SIDEBAR MENU
    # --------------------------------------------------
    "show_sidebar": True,
    "navigation_expanded": True,
    # --------------------------------------------------
    # ICONS (VERY IMPORTANT)
    # --------------------------------------------------
    "icons": {
        "auth": "fas fa-users-cog",
        "auth.User": "fas fa-users",
        "auth.Group": "fas fa-shield-alt",
        "auction_list": "fas fa-gavel",
        "auction_list.Auction": "fas fa-gavel",
        "auction_list.Lot": "fas fa-box",
        "auction_list.Item": "fas fa-tags",
        "auction_list.Category": "fas fa-layer-group",
    },
    # --------------------------------------------------
    # DEFAULT ICONS
    # --------------------------------------------------
    "default_icon_parents": "fas fa-chevron-circle-right",
    "default_icon_children": "fas fa-circle",
    # --------------------------------------------------
    # UI TWEAKS
    # --------------------------------------------------
    "related_modal_active": True,
    "custom_css": None,  # add custom css path if needed
    "custom_js": None,
    "use_google_fonts_cdn": True,
    "changeform_format": "horizontal_tabs",
    "changeform_format_overrides": {
        "auth.user": "collapsible",
    },
    # --------------------------------------------------
    # TABLE UI
    # --------------------------------------------------
    "language_chooser": False,
    # --------------------------------------------------
    # DARK MODE (IMPORTANT)
    # --------------------------------------------------
    "theme": "darkly",  # darkly | cyborg | flatly | minty | lumen
}


# Application definition

INSTALLED_APPS = [
    "jazzmin",
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "Home",
    "auction_list",
    "bids",
    "channels",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
]

ROOT_URLCONF = "AuctionHouse.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [
            BASE_DIR / "templates",
            BASE_DIR / "Home/templates",
            BASE_DIR / "auction_list/templates",
            BASE_DIR / "custom_admin/templates",
            BASE_DIR / "bids/templates",
        ],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "AuctionHouse.wsgi.application"
# ASGI Configuration
ASGI_APPLICATION = "AuctionHouse.asgi.application"

# Channels Layer (for WebSocket)
CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "channels.layers.InMemoryChannelLayer"
        # For production, use Redis:
        # 'BACKEND': 'channels_redis.core.RedisChannelLayer',
        # 'CONFIG': {
        #     "hosts": [('127.0.0.1', 6379)],
        # },
    },
}

# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "Asia/Kolkata"  # Indian Standard Time (IST)

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = "static/"
STATICFILES_DIRS = [os.path.join(BASE_DIR, "static")]

STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

MEDIA_URL = "/media/"
MEDIA_ROOT = os.path.join(BASE_DIR, "media")

MESSAGE_TAGS = {
    messages.DEBUG: "debug",
    messages.INFO: "info",
    messages.SUCCESS: "success",
    messages.WARNING: "warning",
    messages.ERROR: "error",
}

MESSAGE_LEVEL = messages.DEBUG

MESSAGE_STORAGE = "django.contrib.messages.storage.session.SessionStorage"

EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
EMAIL_HOST = "smtp.gmail.com"
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = "meetvaghasiya166@gmail.com"
EMAIL_HOST_PASSWORD = "uycl kjms nuuh bysv"
