"""
Django settings for AuctionHouse project.

Generated by 'django-admin startproject' using Django 5.2.5.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
# Auto-reload trigger
import os
from decouple import config
import dj_database_url
import cloudinary
import cloudinary.uploader
import cloudinary.api
from django.contrib.messages import constants as messages

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure--_lx4*%4c6t#i6a($ec-tet7xvio7qs14)&dkz5xlki30inv3q"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['auction-house-5.onrender.com', 'localhost', '127.0.0.1']

UNFOLD = {
    "SITE_TITLE": "EasyBid Admin",
    "SITE_HEADER": "EasyBid",
    "SITE_URL": "/",
    "SHOW_THEME_SWITCHER": True,
    "SIDEBAR": {
        "show_search": True,
        "show_all_applications": False,
        "navigation": [
            {
                "title": "Auction List",
                "separator": True,
                "items": [
                    {"title": "Auctions", "icon": "gavel", "link": "/admin/auction_list/auction/"},
                    {"title": "Categories", "icon": "grid_view", "link": "/admin/auction_list/catagory/"},
                    {"title": "Invoices", "icon": "receipt_long", "link": "/admin/auction_list/invoice/"},
                    {"title": "Items", "icon": "category", "link": "/admin/auction_list/item/"},
                    {"title": "Lots", "icon": "inventory_2", "link": "/admin/auction_list/lot/"},
                ],
            },
            {
                "title": "Bids",
                "separator": True,
                "items": [
                    {"title": "Bids", "icon": "gavel", "link": "/admin/bids/bid/"},
                    {"title": "Transactions", "icon": "receipt_long", "link": "/admin/bids/transaction/"},
                    {"title": "Wallets", "icon": "category", "link": "/admin/bids/userwallet"},
                    {"title": "Admin Wallet", "icon": "inventory_2", "link": "/admin/bids/adminwallet/"},
                ],
            },
            {
                "title": "Users",
                "separator": True,
                "items": [
                    {"title": "Users", "icon": "gavel", "link": "/admin/auth/user/"},
                ],
            },
            {
                'title':'Profile',
                'items':[
                    {'title':'Profile','icon':'gavel','link':'/admin/Home/profile/'}
                ],
            },
        ],
    },
    "LIST_VIEW": {
        "compact": True,
        "sticky_header": False,
    },
    "FORM": {
        "show_collapsible_help": False,
        "horizontal_fields": False,
        "show_help_text": False,
    },
    "BREADCRUMBS": False,
    "SHOW_FILTERS": True,
    # Remove CHANGELIST_ACTIONS, EXTRA_JS, EXTRA_CSS related to filter_toggle
}

# Application definition

INSTALLED_APPS = [
    "daphne",
    "unfold",
    "unfold.contrib.filters", 
    "unfold.contrib.forms",
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "whitenoise.runserver_nostatic",
    "cloudinary_storage",
    "cloudinary",
    "Home",
    "auction_list",
    "bids",
    "admin_panel",
    "core.apps.CoreConfig",
    "channels",
    # Allauth
    'django.contrib.sites',
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'allauth.socialaccount.providers.google',
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "allauth.account.middleware.AccountMiddleware",
    "AuctionHouse.middleware.SuspendMiddleware",
]

ROOT_URLCONF = "AuctionHouse.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [
            BASE_DIR / "templates",
            BASE_DIR / "Home/templates",
            BASE_DIR / "auction_list/templates",
            BASE_DIR / "custom_admin/templates",
            BASE_DIR / "admin_panel/templates",
            BASE_DIR / "bids/templates",
        ],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

GOOGLE_CLIENT_ID = config('GOOGLE_CLIENT_ID', default='')
GOOGLE_CLIENT_SECRET = config('GOOGLE_CLIENT_SECRET', default='')

SITE_ID = 1

AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',
    'allauth.account.auth_backends.AuthenticationBackend',
]

SOCIALACCOUNT_PROVIDERS = {
    'google': {
        'SCOPE': [
            'profile',
            'email',
        ],
        'AUTH_PARAMS': {
            'access_type': 'online',
            'prompt': 'select_account',
        }
    }
}

SOCIALACCOUNT_LOGIN_ON_GET = True
ACCOUNT_LOGOUT_ON_GET = True
ACCOUNT_AUTHENTICATION_METHOD = 'email'
ACCOUNT_LOGIN_METHODS = {'email'}
ACCOUNT_EMAIL_REQUIRED = True
ACCOUNT_USERNAME_REQUIRED = False
ACCOUNT_EMAIL_VERIFICATION = 'none' # We already handle email OTP during registration
SOCIALACCOUNT_AUTO_SIGNUP = True
SOCIALACCOUNT_EMAIL_AUTHENTICATION = True
SOCIALACCOUNT_EMAIL_AUTHENTICATION_AUTO_CONNECT = True
SOCIALACCOUNT_QUERY_EMAIL = True
SOCIALACCOUNT_LOGIN_REDIRECT_URL = '/home/'
ACCOUNT_SIGNUP_REDIRECT_URL = '/home/'

WSGI_APPLICATION = "AuctionHouse.wsgi.application"
# ASGI Configuration
ASGI_APPLICATION = "AuctionHouse.asgi.application"

# Channels Layer (for WebSocket)
if os.environ.get('REDIS_URL'):
    CHANNEL_LAYERS = {
        "default": {
            "BACKEND": "channels_redis.core.RedisChannelLayer",
            "CONFIG": {
                "hosts": [os.environ.get('REDIS_URL')],
            },
        },
    }
else:
    CHANNEL_LAYERS = {
        "default": {
            "BACKEND": "channels.layers.InMemoryChannelLayer"
        }
    }

# Environment flag provided by Render
IS_PRODUCTION = os.environ.get("RENDER", False)

# Database — uses DATABASE_URL on Render (PostgreSQL), falls back to SQLite for local dev
_DATABASE_URL = os.environ.get("DATABASE_URL")
if _DATABASE_URL:
    DATABASES = {
        "default": dj_database_url.parse(
            _DATABASE_URL,
            conn_max_age=600,
            ssl_require=True,
        )
    }
    # Ensure SSL is passed correctly for psycopg2/psycopg3 on Render
    DATABASES["default"].setdefault("OPTIONS", {})["sslmode"] = "require"
else:
    # Local development — use SQLite (no SSL)
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.sqlite3",
            "NAME": BASE_DIR / "db.sqlite3",
            "OPTIONS": {
                "timeout": 30,
            }
        }
    }


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "Asia/Kolkata"  # Indian Standard Time (IST)

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = "static/"
STATICFILES_DIRS = [os.path.join(BASE_DIR, "static")]

STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# ---------------------------------------------------------------------------
# Cloudinary — persistent media storage (profile images, item images, etc.)
# Set these three values as environment variables on Render:
#   CLOUDINARY_CLOUD_NAME, CLOUDINARY_API_KEY, CLOUDINARY_API_SECRET
# ---------------------------------------------------------------------------
CLOUDINARY_STORAGE = {
    'CLOUD_NAME': os.environ.get('CLOUDINARY_CLOUD_NAME', ''),
    'API_KEY':    os.environ.get('CLOUDINARY_API_KEY', ''),
    'API_SECRET': os.environ.get('CLOUDINARY_API_SECRET', ''),
}

cloudinary.config(
    cloud_name=CLOUDINARY_STORAGE['CLOUD_NAME'],
    api_key=CLOUDINARY_STORAGE['API_KEY'],
    api_secret=CLOUDINARY_STORAGE['API_SECRET'],
    secure=True,
)

# Django 5.x STORAGES dict — replaces deprecated DEFAULT_FILE_STORAGE
if CLOUDINARY_STORAGE['CLOUD_NAME']:
    # On Render: store all uploads on Cloudinary CDN (persistent, survives restarts)
    STORAGES = {
        "default": {
            "BACKEND": "cloudinary_storage.storage.MediaCloudinaryStorage",
        },
        "staticfiles": {
            "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
        },
    }
    MEDIA_URL = f"https://res.cloudinary.com/{CLOUDINARY_STORAGE['CLOUD_NAME']}/"
else:
    # Local dev: save to local media/ directory
    STORAGES = {
        "default": {
            "BACKEND": "django.core.files.storage.FileSystemStorage",
        },
        "staticfiles": {
            "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
        },
    }
    MEDIA_URL = '/media/'

MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

MESSAGE_TAGS = {
    messages.DEBUG: "debug",
    messages.INFO: "info",
    messages.SUCCESS: "success",
    messages.WARNING: "warning",
    messages.ERROR: "error",
}

MESSAGE_LEVEL = messages.DEBUG
MESSAGE_STORAGE = "django.contrib.messages.storage.session.SessionStorage"




EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
EMAIL_HOST = os.environ.get("EMAIL_HOST", "smtp-relay.brevo.com")
EMAIL_PORT = int(os.environ.get("EMAIL_PORT", 587))
EMAIL_USE_TLS = True
EMAIL_HOST_USER = config('EMAIL_HOST_USER', default='a34d24001@smtp-brevo.com')
EMAIL_HOST_PASSWORD = config('EMAIL_HOST_PASSWORD', default='')
# Gmail deliverability: Use a real email address as the 'From' sender.
# IMPORTANT: You MUST verify meetvaghasiya166@gmail.com in your Brevo Dashboard (Senders & IP).
DEFAULT_FROM_EMAIL = os.environ.get("DEFAULT_FROM_EMAIL", "meetvaghasiya166@gmail.com")




# Auction Settings  
WINNER_PAYMENT_TIMEOUT_MINUTES = 3 * 24 * 60  # 3 days

# Razorpay Settings
RAZORPAY_KEY_ID = config('RAZORPAY_KEY_ID', default='')
RAZORPAY_KEY_SECRET = config('RAZORPAY_KEY_SECRET', default='')

# Warehouse Location for Shipping Calculation
WAREHOUSE_CITY = 'Ahmedabad'
WAREHOUSE_STATE = 'Gujarat'

CSRF_TRUSTED_ORIGINS = [
    "https://auction-house-5.onrender.com",
]

if IS_PRODUCTION:
    CSRF_COOKIE_SECURE = True
    SESSION_COOKIE_SECURE = True
    SECURE_SSL_REDIRECT = True
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
else:
    CSRF_COOKIE_SECURE = False
    SESSION_COOKIE_SECURE = False
    SECURE_SSL_REDIRECT = False
    SECURE_PROXY_SSL_HEADER = None

CSRF_COOKIE_SAMESITE = "Lax"
SESSION_COOKIE_SAMESITE = "Lax"


# Required for WebSockets behind proxy
USE_X_FORWARDED_HOST = True
LOGIN_REDIRECT_URL = 'home'