# Generated by Django 5.2.5 on 2026-01-27 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Home", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="theme_color",
            field=models.CharField(
                choices=[
                    ("indigo", "Indigo (Default)"),
                    ("emerald", "Emerald"),
                    ("rose", "Rose"),
                    ("amber", "Amber"),
                    ("cyan", "Cyan"),
                    ("slate", "Slate"),
                    ("violet", "Violet"),
                    ("fuchsia", "Fuchsia"),
                ],
                default="indigo",
                max_length=20,
            ),
        ),
    ]
