# Generated by Django 5.2.5 on 2026-01-27 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Home", "0002_profile_theme_color"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="address",
            field=models.TextField(blank=True, help_text="Shipping address"),
        ),
        migrations.AddField(
            model_name="profile",
            name="bio",
            field=models.TextField(
                blank=True, help_text="Short bio about yourself", max_length=500
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="phone_number",
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name="profile",
            name="website",
            field=models.URLField(blank=True),
        ),
    ]
