# Generated by Django 5.2.5 on 2026-02-05 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Home", "0003_profile_address_profile_bio_profile_phone_number_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="profile_image",
            field=models.ImageField(blank=True, null=True, upload_to="profile_images/"),
        ),
    ]
