# Generated by Django 6.0 on 2026-02-05 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Home", "0004_alter_profile_profile_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="profile_image",
            field=models.ImageField(
                blank=True,
                default="profile_images/default.png",
                null=True,
                upload_to="profile_images/",
            ),
        ),
    ]
