# Generated by Django 5.2.5 on 2026-02-06 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Home", "0005_alter_profile_profile_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="pin_set",
            field=models.BooleanField(
                default=False, help_text="Has user set their transaction PIN?"
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="pin_set_at",
            field=models.DateTimeField(
                blank=True, help_text="When PIN was set", null=True
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="transaction_pin",
            field=models.CharField(
                blank=True, help_text="Hashed transaction PIN", max_length=128
            ),
        ),
    ]
