# Generated by Django 5.2.5 on 2026-02-06 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Home", "0006_profile_pin_set_profile_pin_set_at_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="pin_set",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="pin_set_at",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="transaction_pin",
        ),
    ]
