# Generated by Django 5.2.5 on 2026-02-09 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Home", "0008_profile_pin_set_profile_pin_set_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="city",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="profile",
            name="state",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="profile",
            name="zip_code",
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
