# Generated by Django 5.2.5 on 2026-02-24 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Home", "0009_profile_city_profile_state_profile_zip_code"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="default_profile_image",
            field=models.ImageField(
                blank=True,
                default="media/profile_images/default-image.webp",
                null=True,
                upload_to="media/profile_images/",
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="profile_image",
            field=models.ImageField(
                blank=True, null=True, upload_to="media/profile_images/"
            ),
        ),
    ]
