# Generated by Django 5.2.5 on 2026-02-25 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Home", "0010_remove_default_profile_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="profile_image_base64",
            field=models.TextField(
                blank=True, help_text="Fallback base64 image for Render", null=True
            ),
        ),
    ]
