# Generated by Django 5.2.5 on 2026-03-01 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bids", "0004_pendingpayment_amount_to_pay_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="wallet",
            name="user",
        ),
        migrations.DeleteModel(
            name="Transaction",
        ),
        migrations.DeleteModel(
            name="Wallet",
        ),
    ]
