# Generated by Django 6.0 on 2026-01-11 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auction_list", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="slug",
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
