# Generated by Django 5.2.5 on 2026-01-22 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auction_list", "0002_item_slug"),
    ]

    operations = [
        migrations.AddField(
            model_name="lot",
            name="auto_close_on_end",
            field=models.BooleanField(
                default=True, help_text="Automatically close lot when time expires"
            ),
        ),
        migrations.AddField(
            model_name="lot",
            name="is_timed",
            field=models.BooleanField(
                default=False, help_text="Enable timed auction for this lot"
            ),
        ),
        migrations.AddField(
            model_name="lot",
            name="lot_end_time",
            field=models.DateTimeField(
                blank=True, help_text="When bidding ends for this lot", null=True
            ),
        ),
        migrations.AddField(
            model_name="lot",
            name="lot_start_time",
            field=models.DateTimeField(
                blank=True, help_text="When bidding starts for this lot", null=True
            ),
        ),
    ]
