# Generated by Django 5.2.5 on 2026-01-23 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "auction_list",
            "0003_lot_auto_close_on_end_lot_is_timed_lot_lot_end_time_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="auction",
            name="status",
            field=models.CharField(
                choices=[
                    ("not_started", "Not Started"),
                    ("live", "Live"),
                    ("completed", "Completed"),
                ],
                default="draft",
                max_length=20,
            ),
        ),
    ]
