# Generated by Django 6.0 on 2026-01-25 09:31

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("auction_list", "0005_auctionregister_lotregister"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="lotregister",
            unique_together={("user", "lot")},
        ),
    ]
