# Generated by Django 5.2.5 on 2026-01-25 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auction_list", "0006_alter_lotregister_unique_together"),
    ]

    operations = [
        migrations.AlterField(
            model_name="auction",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("pending", "Pending Approval"),
                    ("approved", "Approved"),
                    ("scheduled", "Scheduled"),
                    ("live", "Live"),
                    ("completed", "Completed"),
                    ("cancelled", "Cancelled"),
                ],
                default="draft",
                max_length=20,
            ),
        ),
    ]
