# Generated by Django 5.2.5 on 2026-01-27 05:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auction_list", "0007_alter_auction_status"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name="auctionregister",
            old_name="register_date",
            new_name="registered_at",
        ),
        migrations.RenameField(
            model_name="lotregister",
            old_name="register_date",
            new_name="registered_at",
        ),
        migrations.AlterUniqueTogether(
            name="lotregister",
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name="lot",
            name="auto_close_on_end",
        ),
        migrations.RemoveField(
            model_name="lot",
            name="is_timed",
        ),
        migrations.RemoveField(
            model_name="lot",
            name="lot_end_time",
        ),
        migrations.RemoveField(
            model_name="lot",
            name="lot_start_time",
        ),
        migrations.AlterField(
            model_name="auction",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("pending", "Pending Approval"),
                    ("approved", "Approved"),
                    ("live", "Live"),
                    ("scheduled", "Scheduled"),
                    ("completed", "Completed"),
                    ("cancelled", "Cancelled"),
                ],
                default="draft",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="auctionregister",
            name="auction",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="registrations",
                to="auction_list.auction",
            ),
        ),
        migrations.AlterField(
            model_name="auctionregister",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="auction_registrations",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="lotregister",
            name="lot",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="registrations",
                to="auction_list.lot",
            ),
        ),
        migrations.AlterField(
            model_name="lotregister",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="lot_registrations",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
