# Generated by Django 5.2.5 on 2026-01-27 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "auction_list",
            "0008_rename_register_date_auctionregister_registered_at_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="lot",
            name="end_time",
            field=models.DateTimeField(
                blank=True, help_text="When the timed auction ends", null=True
            ),
        ),
        migrations.AddField(
            model_name="lot",
            name="idle_timer_start_time",
            field=models.DateTimeField(
                blank=True, help_text="When idle timer started", null=True
            ),
        ),
        migrations.AddField(
            model_name="lot",
            name="idle_timer_started",
            field=models.BooleanField(
                default=False, help_text="Has the idle timer started?"
            ),
        ),
        migrations.AddField(
            model_name="lot",
            name="is_timed",
            field=models.BooleanField(
                default=False, help_text="Is this a timed auction lot?"
            ),
        ),
        migrations.AddField(
            model_name="lot",
            name="last_bid_time",
            field=models.DateTimeField(
                blank=True, help_text="Time of last bid", null=True
            ),
        ),
        migrations.AddField(
            model_name="lot",
            name="min_bid_increment",
            field=models.DecimalField(
                decimal_places=2,
                default=100.0,
                help_text="Minimum bid increment",
                max_digits=10,
            ),
        ),
    ]
