# Generated by Django 5.2.5 on 2026-02-02 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auction_list", "0010_lotchatmessage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lot",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("active", "Active"),
                    ("sold", "Sold"),
                    ("unsold", "Unsold"),
                ],
                default="draft",
                max_length=20,
            ),
        ),
    ]
