# Generated by Django 5.2.5 on 2026-02-07 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auction_list", "0012_invoice"),
    ]

    operations = [
        migrations.AddField(
            model_name="auction",
            name="slug",
            field=models.SlugField(blank=True, max_length=300, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="lot",
            name="slug",
            field=models.SlugField(blank=True, max_length=300, null=True, unique=True),
        ),
    ]
