# Generated by Django 5.2.5 on 2026-02-08 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auction_list", "0014_alter_lot_status_delivery"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoice",
            name="shipping_fee",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name="lot",
            name="shipping_fee",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                help_text="Shipping charges for this lot",
                max_digits=10,
            ),
        ),
    ]
