# Generated by Django 5.2.5 on 2026-02-08 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auction_list", "0015_invoice_shipping_fee_lot_shipping_fee"),
    ]

    operations = [
        migrations.AlterField(
            model_name="delivery",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending Shipment to Warehouse"),
                    ("shipped_to_warehouse", "Shipped to Warehouse"),
                    ("at_warehouse", "At Warehouse"),
                    ("shipped", "Shipped to Buyer"),
                    ("delivered", "Delivered"),
                    ("disputed", "Disputed"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="lot",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("active", "Active"),
                    ("paid", "Paid - Awaiting Shipment"),
                    ("shipped_to_warehouse", "Shipped to Warehouse"),
                    ("at_warehouse", "At Warehouse"),
                    ("shipped", "Shipped to Buyer"),
                    ("sold", "Sold & Delivered"),
                    ("unsold", "Unsold"),
                ],
                default="draft",
                max_length=20,
            ),
        ),
    ]
