# Generated by Django 5.2.5 on 2026-02-09 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auction_list", "0016_alter_delivery_status_alter_lot_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="pickup_otp",
            field=models.CharField(
                blank=True, help_text="OTP for admin pickup", max_length=6, null=True
            ),
        ),
        migrations.AddField(
            model_name="item",
            name="pickup_status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending Pickup"),
                    ("picked_up", "Picked Up"),
                    ("at_warehouse", "At Warehouse"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="item",
            name="shipping_fee",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                help_text="Cost to ship from User to Warehouse",
                max_digits=10,
            ),
        ),
    ]
