# Generated by Django 5.2.5 on 2026-02-10 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auction_list", "0017_item_pickup_otp_item_pickup_status_item_shipping_fee"),
    ]

    operations = [
        migrations.AddField(
            model_name="auction",
            name="reminder_sent",
            field=models.BooleanField(
                default=False, help_text="Has the 10-minute reminder email been sent?"
            ),
        ),
        migrations.AddField(
            model_name="lot",
            name="reminder_sent",
            field=models.BooleanField(
                default=False, help_text="Has the reminder email been sent?"
            ),
        ),
    ]
