# Generated by Django 5.2.5 on 2026-02-10 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auction_list", "0018_auction_reminder_sent_lot_reminder_sent"),
    ]

    operations = [
        migrations.AddField(
            model_name="auction",
            name="is_hot",
            field=models.BooleanField(
                default=False,
                help_text="Is this auction receiving high bid activity (10+ bids in last 10 minutes)?",
            ),
        ),
        migrations.AddField(
            model_name="lot",
            name="is_hot",
            field=models.BooleanField(
                default=False,
                help_text="Is this lot receiving high bid activity (10+ bids in last 10 minutes)?",
            ),
        ),
    ]
