# Generated by Django 5.2.5 on 2026-02-15 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auction_list", "0019_auction_is_hot_lot_is_hot"),
    ]

    operations = [
        migrations.AddField(
            model_name="auction",
            name="start_email_sent",
            field=models.BooleanField(
                default=False, help_text="Has the auction start email been sent?"
            ),
        ),
        migrations.AlterField(
            model_name="auction",
            name="auction_type",
            field=models.CharField(
                choices=[("live", "Live Auction"), ("scheduled", "Scheduled Auction")],
                default="live",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="auction",
            name="is_hot",
            field=models.BooleanField(
                default=False,
                help_text="Is this exception receiving high bid activity (10+ bids in last 10 minutes)?",
            ),
        ),
        migrations.AlterField(
            model_name="auction",
            name="reminder_sent",
            field=models.BooleanField(
                default=False, help_text="Has the 5-minute reminder email been sent?"
            ),
        ),
        migrations.AlterField(
            model_name="item",
            name="pickup_status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending Pickup"),
                    ("picked_up", "Picked Up"),
                    ("at_warehouse", "At Warehouse"),
                    ("delivered", "Delivered to Buyer"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
    ]
