# Generated by Django 5.2.5 on 2026-02-27 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auction_list", "0021_fix_item_status_case"),
    ]

    operations = [
        migrations.AddField(
            model_name="catagory",
            name="requires_document",
            field=models.BooleanField(
                default=False,
                help_text="Does this category require document proofs (e.g. real estate)?",
            ),
        ),
        migrations.AddField(
            model_name="item",
            name="document_proofs",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="List of document proofs like ID, property papers etc.",
            ),
        ),
        migrations.AlterField(
            model_name="item",
            name="status",
            field=models.CharField(
                choices=[
                    ("Pending Approval", "Pending Verification"),
                    ("Available", "In Warehouse"),
                    ("Lotted", "Assigned to Auction"),
                    ("Sold", "Sold"),
                ],
                default="Available",
                max_length=20,
            ),
        ),
    ]
