# Generated by Django 5.2.5 on 2026-02-27 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "auction_list",
            "0022_catagory_requires_document_item_document_proofs_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="estimated_value",
            field=models.DecimalField(decimal_places=2, max_digits=14),
        ),
        migrations.AlterField(
            model_name="lot",
            name="current_bid",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=14),
        ),
        migrations.AlterField(
            model_name="lot",
            name="reserve_price",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Minimum price for sale (optional)",
                max_digits=14,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="lot",
            name="starting_bid",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=14),
        ),
    ]
