# Generated by Django 5.2.5 on 2026-03-03 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "auction_list",
            "0023_alter_item_estimated_value_alter_lot_current_bid_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="invoice",
            name="buyer_premium",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                help_text="Buyer premium charged (admin profit)",
                max_digits=10,
            ),
        ),
        migrations.AlterField(
            model_name="item",
            name="status",
            field=models.CharField(
                choices=[
                    ("Draft", "Draft"),
                    ("Pending Approval", "Pending Verification"),
                    ("Approved", "Approved"),
                    ("Pickup Item", "Pickup Item"),
                    ("Warehouse", "Warehouse"),
                    ("Lotted", "Assigned to Auction"),
                    ("Sold", "Sold"),
                    ("Rejected", "Rejected"),
                ],
                default="Pending Approval",
                max_length=20,
            ),
        ),
    ]
