# Generated by Django 5.2.5 on 2026-03-03 10:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auction_list", "0024_proxy_bid_buyer_premium"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lot",
            name="lot_catagory",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="auction_list.catagory",
            ),
        ),
        migrations.AlterField(
            model_name="lot",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("active", "Active"),
                    ("pending_payment", "Pending Payment"),
                    ("paid", "Paid - Awaiting Shipment"),
                    ("shipped_to_warehouse", "Shipped to Warehouse"),
                    ("at_warehouse", "At Warehouse"),
                    ("shipped", "Shipped to Buyer"),
                    ("sold", "Sold & Delivered"),
                    ("unsold", "Unsold"),
                ],
                default="draft",
                max_length=20,
            ),
        ),
    ]
