# Generated by Django 5.2.5 on 2026-03-04 05:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auction_list", "0025_alter_lot_lot_catagory_alter_lot_status"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="catagory",
            name="is_immovable",
            field=models.BooleanField(
                default=False,
                help_text="Is this category for immovable property (e.g., Real Estate)? Skips delivery and uses property sale workflow.",
            ),
        ),
        migrations.AlterField(
            model_name="lot",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("active", "Active"),
                    ("pending_payment", "Pending Payment"),
                    ("paid", "Paid - Awaiting Shipment"),
                    ("shipped_to_warehouse", "Shipped to Warehouse"),
                    ("at_warehouse", "At Warehouse"),
                    ("shipped", "Shipped to Buyer"),
                    ("sold", "Sold & Delivered"),
                    ("unsold", "Unsold"),
                    ("property_sale", "Property Sale in Progress"),
                ],
                default="draft",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="PropertySale",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("emd_pending", "EMD Payment Pending"),
                            ("emd_paid", "EMD Paid"),
                            ("documents_pending", "Documents Pending"),
                            ("documents_submitted", "Documents Submitted"),
                            ("documents_verified", "Documents Verified"),
                            ("agreement_pending", "Agreement Pending"),
                            ("agreement_signed", "Agreement Signed"),
                            ("final_payment_pending", "Final Payment Pending"),
                            ("final_payment_done", "Final Payment Done"),
                            ("registration_pending", "Registration Pending"),
                            ("registration_done", "Registration Done"),
                            ("possession_transferred", "Possession Transferred"),
                            ("completed", "Completed"),
                        ],
                        default="emd_pending",
                        max_length=30,
                    ),
                ),
                (
                    "emd_percentage",
                    models.DecimalField(
                        decimal_places=2,
                        default=10.0,
                        help_text="EMD as % of winning bid",
                        max_digits=5,
                    ),
                ),
                (
                    "emd_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Auto-calculated EMD amount",
                        max_digits=14,
                    ),
                ),
                ("emd_paid", models.BooleanField(default=False)),
                (
                    "emd_payment_id",
                    models.CharField(
                        blank=True,
                        help_text="Razorpay payment ID for EMD",
                        max_length=100,
                    ),
                ),
                (
                    "emd_deadline",
                    models.DateTimeField(
                        blank=True,
                        help_text="Deadline for EMD payment (default 72h)",
                        null=True,
                    ),
                ),
                (
                    "buyer_documents",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Uploaded buyer KYC documents",
                    ),
                ),
                (
                    "seller_documents",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Uploaded seller property documents",
                    ),
                ),
                ("documents_verified_at", models.DateTimeField(blank=True, null=True)),
                (
                    "documents_rejection_reason",
                    models.TextField(
                        blank=True, help_text="Reason if documents are rejected"
                    ),
                ),
                (
                    "agreement_file",
                    models.CharField(
                        blank=True,
                        help_text="Path/URL to generated sale agreement PDF",
                        max_length=500,
                    ),
                ),
                ("buyer_agreed", models.BooleanField(default=False)),
                ("seller_agreed", models.BooleanField(default=False)),
                ("agreement_signed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "final_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Winning bid - EMD",
                        max_digits=14,
                    ),
                ),
                (
                    "final_payment_id",
                    models.CharField(
                        blank=True,
                        help_text="Razorpay payment ID for final payment",
                        max_length=100,
                    ),
                ),
                ("final_payment_at", models.DateTimeField(blank=True, null=True)),
                (
                    "stamp_duty",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Stamp duty amount",
                        max_digits=14,
                    ),
                ),
                (
                    "registration_charges",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Registration charges",
                        max_digits=14,
                    ),
                ),
                (
                    "registration_number",
                    models.CharField(
                        blank=True,
                        help_text="Government registration number",
                        max_length=100,
                    ),
                ),
                ("registration_date", models.DateTimeField(blank=True, null=True)),
                (
                    "sale_deed_file",
                    models.CharField(
                        blank=True,
                        help_text="Path/URL to uploaded sale deed",
                        max_length=500,
                    ),
                ),
                ("possession_date", models.DateTimeField(blank=True, null=True)),
                (
                    "possession_letter_file",
                    models.CharField(
                        blank=True,
                        help_text="Path/URL to possession letter",
                        max_length=500,
                    ),
                ),
                (
                    "platform_commission_pct",
                    models.DecimalField(
                        decimal_places=2,
                        default=2.0,
                        help_text="Platform commission % for real estate",
                        max_digits=5,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "admin_notes",
                    models.TextField(blank=True, help_text="Internal admin notes"),
                ),
                (
                    "buyer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="property_purchases",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "documents_verified_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Admin who verified documents",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="verified_property_docs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "lot",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="property_sale",
                        to="auction_list.lot",
                    ),
                ),
                (
                    "seller",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="property_sales",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Property Sale",
                "verbose_name_plural": "Property Sales",
                "ordering": ["-created_at"],
            },
        ),
    ]
